### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by clogher** [lextoumbourou/plugin.video.udacity#1]
Hi,

I am currently using kodi 16.1 and I got this error :

> 12:17:31 T:140189544478464  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
> 12:17:31 T:140189544478464 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
> 12:17:33 T:140189544478464 WARNING: Previous line repeats 1 times.
> 12:17:33 T:140189544478464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.KeyError'>
>                                             Error Contents: "name='XSRF-TOKEN', domain=None, path=None"
>                                             Traceback (most recent call last):
>                                               File "/home/sam/.kodi/addons/plugin.video.udacity/addon.py", line 209, in <module>
>                                                 plugin.run()
>                                               File "/home/sam/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
>                                                 items = self._dispatch(self.request.path)
>                                               File "/home/sam/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
>                                                 listitems = view_func(**items)
>                                               File "/home/sam/.kodi/addons/plugin.video.udacity/addon.py", line 25, in index
>                                                 if auth.authenticate(username, password):
>                                               File "/home/sam/.kodi/addons/plugin.video.udacity/resources/lib/udacity.py", line 232, in authenticate
>                                                 if not self.get_xsrf_token(force=True):
>                                               File "/home/sam/.kodi/addons/plugin.video.udacity/resources/lib/udacity.py", line 215, in get_xsrf_token
>                                                 self.auth_stored['xsrf_token'] = r.cookies['XSRF-TOKEN']
>                                               File "/home/sam/.kodi/addons/script.module.requests/lib/requests/cookies.py", line 287, in __getitem__
>                                                 return self._find_no_duplicates(name)
>                                               File "/home/sam/.kodi/addons/script.module.requests/lib/requests/cookies.py", line 345, in _find_no_duplicates
>                                                 raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
>                                             KeyError: "name='XSRF-TOKEN', domain=None, path=None"
>                                             -->End of Python script error report<--
> 12:17:33 T:140192270489920   ERROR: GetDirectory - Error getting plugin://plugin.video.udacity/
> 12:17:33 T:140192270489920   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.udacity/) failed

I think the authentication has changed and they does not use anymore XSRF-TOKEN.

**Comment by tzeroem** [comment]
I have same error...
